application: cs2jweb
version: os-2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /static
  static_dir: public/static

- url: /.*
  script: djangoappengine.main.application
